theme: jekyll-theme-cayman
title: "CS294 Science and Technology of Decentralization and Decentralized Intelligence"
description: Spring 2022
show_downloads: false
github:
  is_project_page: false
plugins:
  - jekyll-redirect-from
